syntax = "proto3";
//package code generated by devx  DO NOT EDIT.
package   sampleModule.samplePackage;

option  go_package ="sampleModule/samplePackage";

message HelloRequest {
    string msg = 1;
}

message HelloReply {
    string msg = 1;
    string code = 2;
}

service Sample.Pb {
    rpc SayHello (HelloRequest) returns (HelloReply);
}
